export enum NotificationMessage {
  // RequestAccepted = 'REQUEST_ACCEPTED',
  // RequestRejected = 'REQUEST_REJECTED',
  // RequestedAppointment = 'REQUESTED_APPOINTMENT',
  // RejectedAppointment = 'REJECTED_APPOINTMENT',
  // AcceptedVA = 'ACCEPTED_VA',
  // RejectedVA = 'REJECTED_VA',
  // RescheduleVA = 'RESCHEDULE_VA',
  // RequestedVA = 'REQUESTED_VA',
  // FiveMinBeforeVA = 'FIVE_MIN_BEFORE_VA',
  // SignOff = 'SIGN_OFF',
  // ActivityLogRequest = 'ACTIVITY_LOG_REQUEST',
  // ActivityLogReview = 'ACTIVITY_LOG_REVIEW',
  // ActivityLogApproved = 'ACTIVITY_LOG_APPROVED',
  // ActivityLogRejected = 'ACTIVITY_LOG_REJECTED',
  // PausedAppointment = 'PAUSED_APPOINTMENT',
  // InsufficientFirstHourPayment = 'INSUFFICIENT_FIRST_HOUR_PAYMENT',
  // ResumeAppointment = 'RESUME_APPOINTMENT',
  BidOverbid = 'BID_OVERBID',
}
