export const farmProductTypesSuggestions = [
  { label: 'Wheat', value: 'Wheat' },
  { label: 'Rice', value: 'Rice' },
  { label: 'Corn', value: 'Corn' },
  { label: 'Potatoes', value: 'Potatoes' },
  { label: 'Tomatoes', value: 'Tomatoes' },
  { label: 'Carrots', value: 'Carrots' },
  { label: 'Onions', value: 'Onions' },
  { label: 'Watermelons', value: 'Watermelons' },
  { label: 'Milk', value: 'Milk' },
  { label: 'Eggs', value: 'Eggs' },
  { label: 'Buckwheat', value: 'Buckwheat' },
  { label: 'Chicken', value: 'Chicken' },
  { label: 'Beef', value: 'Beef' },
  { label: 'Pork', value: 'Pork' },
  { label: 'Cheese', value: 'Cheese' },
  { label: 'Yogurt', value: 'Yogurt' },
  { label: 'Honey', value: 'Honey' },
  { label: 'Wool', value: 'Wool' }
];
