export enum NotificationMessage {
  BidOverbid = 'BID_OVERBID',
  ResumeAppointment = 'RESUME_APPOINTMENT',
  AuctionStartSoon = 'AUCTION_START_SOON',
  AuctionStarted = 'AUCTION_STARTED',
  FarmerAuctionEndSoon = 'FARMER_AUCTION_END_SOON',
  BusinessmanAuctionEndSoon = 'BUSINESSMAN_AUCTION_END_SOON',
  AuctionEndedNoBids = 'AUCTION_ENDED_NO_BIDS',
  AuctionEndedWithBids = 'AUCTION_ENDED_WITH_BIDS',
  BusinessmanAuctionWon = 'BUSINESSMAN_AUCTION_WON',
  BusinessmanAuctionPaymentOverdue = 'BUSINESSMAN_AUCTION_PAYMENT_OVERDUE',
  FarmerAuctionPaymentOverdue = 'FARMER_AUCTION_PAYMENT_OVERDUE',
  DeliveryOrderPaid = 'DELIVERY_ORDER_PAID',
  DeclinedDeliveryOffer = 'DECLINED_DELIVERY_OFFER',
  AcceptedDeliveryOffer = 'ACCEPTED_DELIVERY_OFFER',
  DriverAcceptedDelivery = 'DRIVER_ACCEPTED_DELIVERY',
  DriverArriveToFarm = 'DRIVER_ARRIVE_TO_FARM',
  DriverLoading = 'DRIVER_LOADING',
  DriverOnTheWay = 'DRIVER_ON_THE_WAY',
  DriverUnloading = 'DRIVER_UNLOADING',
  DriverArriveToBusiness = 'DRIVER_ARRIVE_TO_BUSINESS',
  DriverEndedDelivery = 'DRIVER_ENDED_DELIVERY',
}
